### ISSUE TITLE
Python script - Pressing s to save the preview not working

### ISSUE THREAD

**Issue by sundaram75** [ryanpeach/openscan#10]
OS - Ubuntu - 64 bit
Python version - 2.7.10
Steps to reproduce -
1. Run the python script script.py
2. Use printout of the scantemplate.pdf and hold against camera and adjust orientation till preview window appears.
3. Try saving the preview generated by pressing the 's' key.
4. Preview image is not saved as desired.

**Comment by ryanpeach** [comment]
Resolved in your pull request.
