### ISSUE TITLE
findInnerBorder needs better definition.

### ISSUE THREAD

**Issue by ryanpeach** [ryanpeach/openscan#2]
It randomly adds +3 to the output, which is then corrected with a -2 in ln.77. Also needs to insure support for marking focus points and reference points. Be sure it highlights each correctly.

**Comment by sundaram75** [comment]
Hi Ryan,
                 This is cool. I would like to contribute to this project. Could you please guide me on getting started and collaborating on this ?
Thanks
Sundaram

**Comment by ryanpeach** [comment]
Hi sundaram!
Cool of you to want to contribute! I'm about to push an update to the C++ branch which contains a big update to the Main.cpp file. Right now, all I really need is tests tests tests of every method, and commenting so that its all understandable. The wiki has some details as to script.py, if you want to see what the project will do in the end go to the master branch, print a template, run that code, and you should see it work.
Feel free to ask any questions and give any suggestions! The C++ will be done very soon, followed by a wiki update and then moving on to the Android branch as well as a couple of the feature branches. I'll post more often to inform you about features I want to add.
Just curious, how did you here about this project?
Regards,
Ryan Peach
On Nov 2, 2015 5:07 AM, sundaram75 notifications@github.com wrote:Hi Ryan,
                 This is cool. I would like to contribute to this project. Could you please guide me on getting started and collaborating on this ?
Thanks
Sundaram

**Comment by ryanpeach** [comment]
sundaram,

I just updated the wiki and pushed my commits which include better documentation on geometry.hpp. I also deleted unnecessary branches. Let me know if you need any more help!

**Comment by ryanpeach** [comment]
Hey @sundaram75 I've sent you several messages on your gmail, just wanted to make sure you are getting them and they aren't going to spam.

**Comment by ryanpeach** [comment]
I fixed this a while back.
