### ISSUE TITLE
Check time complexity of all methods. Convert from using vectors to lists.

### ISSUE THREAD

**Issue by ryanpeach** [ryanpeach/openscan#6]
The extensive use of vectors instead of lists in OpenCV make this code have much larger time complexity than necessary. It is my hope that we can convert to using lists wherever possible. Research this further.

**Comment by erip** [comment]
Can you explain this? What makes `std::list` faster than `std::vector` in OpenCV?

**Comment by ryanpeach** [comment]
It's not really a matter of speed, as much as it is a matter of standardization. This is actually a closed issue, sorry for not updating it. Basically the app uses a lot of library functions I've made myself, and I'm learning C++ in the process, so unless otherwise specifically necessary I want to be able to write them all using OpenCV's most used format for contours (which is vector<Point> in OpenCV) and specialize most methods to use this input/output format.

**Comment by ryanpeach** [comment]
Our main data types are:

``` cpp
typedef vector<Point> cnt  // an ordered vector of points is a contour or poly
typedef vector<Point> Points  // the same as cnt but implied unordered
class Fp  // which is a class which describes what the wiki calls "Focus Points"
typedef vector<Fp> Fps  // Imagine this as a "contour" of Fp's
vector<cnt>  // This is for a set of contours
struct Cnts  // holds a set of contours and their hierarchy together, rarely used.
```
